# scan qr code
# open link         https://ordering.foodsphere.com/portals/{portal_id}
# get token from    https://ordering.foodsphere.com/api/portals/{portal_id}
# redirect          https://ordering.foodsphere.com headers: authentication's token { bill_id: "...", consumer_id: "..." }
# request to        https://ordering.foodsphere.com/api/*
# opaque token => meaningless string
#
# # การป้องกัน QR code โต๊ะ
# - เมื่อลูกค้าสแกน QR code จะเป็นการเปิดโต๊ะ
# - โต๊ะที่เปิดแล้วจะมี รหัส เหมือนเลขห้องเวลาสร้างเกมเล่นกับเพือน
# - คนถัดไปที่มาสแกนจะต้องใส่ รหัส เพื่อเข้าร่วมโต๊ะ
# - คนที่เข้าร่วมโต๊ะแล้ว จะสแกน QR code เดิมเข้าได้โดยไม่ต้องใส่ รหัส เพราะใช้ cookie ในการจำ
# - คนที่เข้าร่วมโต๊ะแล้ว สามารถสร้าง QR code พิเศษเพื่อให้คนอื่นแสกนได้ คนที่สแกนจะเข้าร่วมโต๊ะได้เลยไม่ต้องใส่ รหัส
# - รหัสจะถูกสุ่มใหม่ทุกครั้งที่เปิดโต๊ะ ป้องกันลูกค้าเก่า

@portal_id = ac0b745f-ecd0-46f2-b042-6e8d5f6ee576
@menu_id_1 = 1
@menu_id_2 = 2
##################################################
# @name get_token

POST {{host}}/auth/self-ordering/token?portal_id={{portal_id}}

##################################################
@jwt = {{get_token.response.body.$.access_token}}
##################################################
# @name list_portal

GET {{host}}/self-ordering/portals
Authorization: Bearer {{jwt}}

##################################################
# @name me

GET {{host}}/self-ordering/me
Authorization: Bearer {{jwt}}

##################################################
# @name create_order_1

POST {{host}}/self-ordering/orders
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "items": [
    {
      "menu_id": {{menu_id_1}},
      "quantity": 5
    },
    {
      "menu_id": {{menu_id_2}},
      "quantity": 5
    }
  ]
}

##################################################
@order_id_1 = {{create_order_1.response.body.$.id}}
##################################################
# @name list_orders

GET {{host}}/self-ordering/orders
Authorization: Bearer {{jwt}}

##################################################