@portal_id =
##################################################
# @name staff_token

GET {{host}}/auth/staff/token?portal_id={{portal_id}}

##################################################
@jwt = {{staff_token.response.body.$.access_token}}
##################################################
