// <auto-generated />
using System;
using FoodSphere.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodSphere.Npgsql.Helper.Migrations
{
    [DbContext(typeof(FoodSphereDbContext))]
    [Migration("20260318063658_2026.03.18-13.36.43")]
    partial class _20260318133643
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodSphere.Common.Entity.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsumerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("IssuerId")
                        .HasColumnType("smallint");

                    b.Property<short?>("Pax")
                        .HasColumnType("smallint");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<short>("TableId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("ConsumerUserId");

                    b.HasIndex("RestaurantId", "BranchId", "IssuerId");

                    b.HasIndex("RestaurantId", "BranchId", "TableId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.BillMember", b =>
                {
                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BillId", "Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("BillId", "ConsumerId")
                        .IsUnique();

                    b.ToTable("BillMember");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Branch", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("ClosingTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("OpeningTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Id");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.BranchStaff", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<string>("MasterId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "MasterId");

                    b.HasIndex("MasterId");

                    b.ToTable("BranchStaff");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.BranchStaffRole", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<string>("MasterId")
                        .HasColumnType("text");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "MasterId", "RoleId");

                    b.HasIndex("RestaurantId", "RoleId");

                    b.ToTable("BranchStaffRole");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.ConsumerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("ConsumerUser");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Coupon", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FixedDiscount")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxUsage")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PercentageDiscount")
                        .HasColumnType("numeric(7,4)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupon");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Ingredient", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.IngredientTag", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("IngredientId")
                        .HasColumnType("smallint");

                    b.Property<short>("TagId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "IngredientId", "TagId");

                    b.HasIndex("RestaurantId", "TagId");

                    b.ToTable("IngredientTag");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.MasterUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Menu", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.MenuComponent", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("ParentMenuId")
                        .HasColumnType("smallint");

                    b.Property<short>("ChildMenuId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "ParentMenuId", "ChildMenuId");

                    b.HasIndex("RestaurantId", "ChildMenuId");

                    b.ToTable("MenuComponent");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.MenuIngredient", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("MenuId")
                        .HasColumnType("smallint");

                    b.Property<short>("IngredientId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "MenuId", "IngredientId");

                    b.HasIndex("RestaurantId", "IngredientId");

                    b.ToTable("MenuIngredient");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.MenuTag", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("MenuId")
                        .HasColumnType("smallint");

                    b.Property<short>("TagId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "MenuId", "TagId");

                    b.HasIndex("RestaurantId", "TagId");

                    b.ToTable("MenuTag");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Order", b =>
                {
                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<short?>("BillMemberId")
                        .HasColumnType("smallint");

                    b.Property<short?>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("IssuerId")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BillId", "Id");

                    b.HasIndex("BillId", "BillMemberId");

                    b.HasIndex("RestaurantId", "BranchId", "IssuerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.OrderItem", b =>
                {
                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<short>("OrderId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("MenuId")
                        .HasColumnType("smallint");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PriceSnapshot")
                        .HasColumnType("integer");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BillId", "OrderId", "Id");

                    b.HasIndex("RestaurantId", "MenuId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.OrderingPortal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("MaxUsage")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("UsageCount")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan?>("ValidDuration")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("OrderingPortal");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Payment", b =>
                {
                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BillId", "Id");

                    b.ToTable("Payment");

                    b.HasDiscriminator<string>("PaymentMethod").HasValue("Payment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "page.order"
                        },
                        new
                        {
                            Id = 2,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "page.table"
                        },
                        new
                        {
                            Id = 2000,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ingredient.create"
                        },
                        new
                        {
                            Id = 2010,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ingredient.read"
                        },
                        new
                        {
                            Id = 2020,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ingredient.update"
                        },
                        new
                        {
                            Id = 3000,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "menu.create"
                        },
                        new
                        {
                            Id = 3010,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "menu.update"
                        },
                        new
                        {
                            Id = 5000,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "stock-transaction.read"
                        },
                        new
                        {
                            Id = 5010,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "stock-transaction.create"
                        },
                        new
                        {
                            Id = 6000,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "table.create"
                        },
                        new
                        {
                            Id = 6010,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "table.update"
                        },
                        new
                        {
                            Id = 7000,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "order.create"
                        },
                        new
                        {
                            Id = 7010,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "order.get"
                        },
                        new
                        {
                            Id = 7020,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "order.list"
                        },
                        new
                        {
                            Id = 7030,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "order.update"
                        },
                        new
                        {
                            Id = 8000,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "dashboard.read"
                        },
                        new
                        {
                            Id = 9000,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "role.create"
                        },
                        new
                        {
                            Id = 9010,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "role.read"
                        },
                        new
                        {
                            Id = 9020,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "role.update"
                        },
                        new
                        {
                            Id = 9030,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "role.delete"
                        },
                        new
                        {
                            Id = 1000,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "restaurant.setting.read"
                        },
                        new
                        {
                            Id = 1010,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "restaurant.setting.update"
                        },
                        new
                        {
                            Id = 4000,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "branch.setting.read"
                        },
                        new
                        {
                            Id = 4010,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "branch.setting.update"
                        });
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Queuing", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Pax")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Queuing");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeAccountId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.RestaurantStaff", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<string>("MasterId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "MasterId");

                    b.HasIndex("MasterId");

                    b.ToTable("RestaurantStaff");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.RestaurantStaffRole", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<string>("MasterId")
                        .HasColumnType("text");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "MasterId", "RoleId");

                    b.HasIndex("RestaurantId", "RoleId");

                    b.ToTable("RestaurantStaffRole");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Role", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Id");

                    b.HasIndex("RestaurantId", "Name")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.RolePermission", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.ServiceRequest", b =>
                {
                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BillId", "Id");

                    b.ToTable("ServiceRequest");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.StockTransaction", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("IngredientId")
                        .HasColumnType("smallint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<short?>("OrderId")
                        .HasColumnType("smallint");

                    b.Property<short?>("OrderItemId")
                        .HasColumnType("smallint");

                    b.HasKey("RestaurantId", "BranchId", "Id");

                    b.HasIndex("RestaurantId", "IngredientId");

                    b.HasIndex("BillId", "OrderId", "OrderItemId");

                    b.ToTable("StockTransaction");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Table", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "Id");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Tag", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Id");

                    b.HasIndex("RestaurantId", "Name")
                        .IsUnique();

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.WorkerPortal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("MaxUsage")
                        .HasColumnType("smallint");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("UsageCount")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan?>("ValidDuration")
                        .HasColumnType("interval");

                    b.Property<short>("WorkerId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "BranchId", "WorkerId");

                    b.ToTable("WorkerPortal");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.WorkerRole", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<short>("WorkerId")
                        .HasColumnType("smallint");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "WorkerId", "RoleId");

                    b.HasIndex("RestaurantId", "RoleId");

                    b.ToTable("WorkerRole");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.WorkerUser", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "Id");

                    b.ToTable("WorkerUser");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.CashPayment", b =>
                {
                    b.HasBaseType("FoodSphere.Common.Entity.Payment");

                    b.HasDiscriminator().HasValue("cash");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.StripePayment", b =>
                {
                    b.HasBaseType("FoodSphere.Common.Entity.Payment");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("stripe");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Bill", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.ConsumerUser", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoodSphere.Common.Entity.ConsumerUser", null)
                        .WithMany("Bills")
                        .HasForeignKey("ConsumerUserId");

                    b.HasOne("FoodSphere.Common.Entity.WorkerUser", "Issuer")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "BranchId", "IssuerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoodSphere.Common.Entity.Table", "Table")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "BranchId", "TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consumer");

                    b.Navigation("Issuer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.BillMember", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Bill", "Bill")
                        .WithMany("Members")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.ConsumerUser", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bill");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Branch", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Restaurant", "Restaurant")
                        .WithMany("Branches")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FoodSphere.Common.Entity.Contact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("BranchRestaurantId")
                                .HasColumnType("uuid");

                            b1.Property<short>("BranchId")
                                .HasColumnType("smallint");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.HasKey("BranchRestaurantId", "BranchId");

                            b1.ToTable("Branch");

                            b1.WithOwner()
                                .HasForeignKey("BranchRestaurantId", "BranchId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.BranchStaff", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.MasterUser", "Master")
                        .WithMany("ManagedBranches")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Branch", "Branch")
                        .WithMany("BranchStaffs")
                        .HasForeignKey("RestaurantId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Master");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.BranchStaffRole", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.BranchStaff", "Staff")
                        .WithMany("Roles")
                        .HasForeignKey("RestaurantId", "BranchId", "MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Ingredient", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Restaurant", "Restaurant")
                        .WithMany("Ingredients")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.IngredientTag", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Ingredient", "Ingredient")
                        .WithMany("Tags")
                        .HasForeignKey("RestaurantId", "IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Tag", "Tag")
                        .WithMany("IngredientTags")
                        .HasForeignKey("RestaurantId", "TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Menu", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Restaurant", "Restaurant")
                        .WithMany("Menus")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.MenuComponent", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Menu", "ChildMenu")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "ChildMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Menu", "ParentMenu")
                        .WithMany("Components")
                        .HasForeignKey("RestaurantId", "ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildMenu");

                    b.Navigation("ParentMenu");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.MenuIngredient", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Ingredient", "Ingredient")
                        .WithMany("MenuIngredients")
                        .HasForeignKey("RestaurantId", "IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Menu", "Menu")
                        .WithMany("Ingredients")
                        .HasForeignKey("RestaurantId", "MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.MenuTag", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Menu", "Menu")
                        .WithMany("Tags")
                        .HasForeignKey("RestaurantId", "MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Tag", "Tag")
                        .WithMany("MenuTags")
                        .HasForeignKey("RestaurantId", "TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Order", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Bill", "Bill")
                        .WithMany("Orders")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.BillMember", "BillMember")
                        .WithMany("Orders")
                        .HasForeignKey("BillId", "BillMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoodSphere.Common.Entity.WorkerUser", "Issuer")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "BranchId", "IssuerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bill");

                    b.Navigation("BillMember");

                    b.Navigation("Issuer");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.OrderItem", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("BillId", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.OrderingPortal", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Bill", "Bill")
                        .WithMany("Portals")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Payment", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Queuing", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.ConsumerUser", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoodSphere.Common.Entity.Branch", "Branch")
                        .WithMany("Queuings")
                        .HasForeignKey("RestaurantId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Restaurant", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.MasterUser", "Owner")
                        .WithMany("OwnedRestaurants")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FoodSphere.Common.Entity.Contact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurant");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.RestaurantStaff", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.MasterUser", "Master")
                        .WithMany("ManagedRestaurants")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Restaurant", "Restaurant")
                        .WithMany("Staffs")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Master");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.RestaurantStaffRole", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.RestaurantStaff", "Staff")
                        .WithMany("Roles")
                        .HasForeignKey("RestaurantId", "MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Role", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.RolePermission", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RestaurantId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.ServiceRequest", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.StockTransaction", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Branch", null)
                        .WithMany("IngredientStocks")
                        .HasForeignKey("RestaurantId", "BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("BillId", "OrderId", "OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ingredient");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Table", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Branch", "Branch")
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Tag", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Restaurant", null)
                        .WithMany("Tags")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.WorkerPortal", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.WorkerUser", "WorkerUser")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "BranchId", "WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkerUser");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.WorkerRole", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.WorkerUser", "Worker")
                        .WithMany("Roles")
                        .HasForeignKey("RestaurantId", "BranchId", "WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.WorkerUser", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.Branch", "Branch")
                        .WithMany("Workers")
                        .HasForeignKey("RestaurantId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.MasterUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.MasterUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entity.MasterUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FoodSphere.Common.Entity.MasterUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Bill", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Portals");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.BillMember", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Branch", b =>
                {
                    b.Navigation("BranchStaffs");

                    b.Navigation("IngredientStocks");

                    b.Navigation("Queuings");

                    b.Navigation("Tables");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.BranchStaff", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.ConsumerUser", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Ingredient", b =>
                {
                    b.Navigation("MenuIngredients");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.MasterUser", b =>
                {
                    b.Navigation("ManagedBranches");

                    b.Navigation("ManagedRestaurants");

                    b.Navigation("OwnedRestaurants");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Menu", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Ingredients");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Restaurant", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Ingredients");

                    b.Navigation("Menus");

                    b.Navigation("Staffs");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.RestaurantStaff", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.Tag", b =>
                {
                    b.Navigation("IngredientTags");

                    b.Navigation("MenuTags");
                });

            modelBuilder.Entity("FoodSphere.Common.Entity.WorkerUser", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
