// <auto-generated />
using System;
using FoodSphere.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodSphere.Migrator.Npgsql.Migrations
{
    [DbContext(typeof(FoodSphereDbContext))]
    [Migration("20260205012046_2026.02.05-08.20.38")]
    partial class _20260205082038
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodSphere.Common.Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("IssuerId")
                        .HasColumnType("smallint");

                    b.Property<short?>("Pax")
                        .HasColumnType("smallint");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<short>("TableId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("RestaurantId", "BranchId", "IssuerId");

                    b.HasIndex("RestaurantId", "BranchId", "TableId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.BillMember", b =>
                {
                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BillId", "Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("BillMember");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Branch", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("ClosingTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("OpeningTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.ConsumerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ConsumerUser");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Coupon", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FixedDiscount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsage")
                        .HasColumnType("integer");

                    b.Property<decimal>("PercentageDiscount")
                        .HasColumnType("numeric(7,4)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Code");

                    b.ToTable("Coupon");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.IngredientTag", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("IngredientId")
                        .HasColumnType("smallint");

                    b.Property<string>("TagId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "IngredientId", "TagId");

                    b.HasIndex("RestaurantId", "TagId");

                    b.ToTable("IngredientTag");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Manager", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<string>("MasterId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "MasterId");

                    b.HasIndex("MasterId");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.ManagerRole", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<string>("ManagerId")
                        .HasColumnType("text");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "ManagerId", "RoleId");

                    b.HasIndex("RestaurantId", "RoleId");

                    b.ToTable("ManagerRole");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.MasterUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Menu", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.MenuComponent", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("ParentMenuId")
                        .HasColumnType("smallint");

                    b.Property<short>("ChildMenuId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "ParentMenuId", "ChildMenuId");

                    b.HasIndex("RestaurantId", "ChildMenuId");

                    b.ToTable("MenuComponent");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.MenuIngredient", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("MenuId")
                        .HasColumnType("smallint");

                    b.Property<short>("IngredientId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "MenuId", "IngredientId");

                    b.HasIndex("RestaurantId", "IngredientId");

                    b.ToTable("MenuIngredient");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.MenuTag", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("MenuId")
                        .HasColumnType("smallint");

                    b.Property<string>("TagId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "MenuId", "TagId");

                    b.HasIndex("RestaurantId", "TagId");

                    b.ToTable("MenuTag");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Order", b =>
                {
                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<short?>("BillMemberId")
                        .HasColumnType("smallint");

                    b.Property<short?>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("IssuerId")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BillId", "Id");

                    b.HasIndex("BillId", "BillMemberId");

                    b.HasIndex("RestaurantId", "BranchId", "IssuerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("OrderId")
                        .HasColumnType("smallint");

                    b.Property<short>("MenuId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PriceSnapshot")
                        .HasColumnType("integer");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BillId", "RestaurantId", "OrderId", "MenuId");

                    b.HasIndex("BillId", "OrderId");

                    b.HasIndex("RestaurantId", "MenuId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 2000,
                            Name = "ingredient.create"
                        },
                        new
                        {
                            Id = 2010,
                            Name = "ingredient.read"
                        },
                        new
                        {
                            Id = 2020,
                            Name = "ingredient.update"
                        },
                        new
                        {
                            Id = 3000,
                            Name = "menu.create"
                        },
                        new
                        {
                            Id = 3010,
                            Name = "menu.update"
                        },
                        new
                        {
                            Id = 5000,
                            Name = "stock.read"
                        },
                        new
                        {
                            Id = 5010,
                            Name = "stock.update"
                        },
                        new
                        {
                            Id = 6000,
                            Name = "table.create"
                        },
                        new
                        {
                            Id = 6010,
                            Name = "table.update"
                        },
                        new
                        {
                            Id = 7000,
                            Name = "order.create"
                        },
                        new
                        {
                            Id = 7010,
                            Name = "order.get"
                        },
                        new
                        {
                            Id = 7020,
                            Name = "order.list"
                        },
                        new
                        {
                            Id = 7030,
                            Name = "order.update"
                        },
                        new
                        {
                            Id = 8000,
                            Name = "dashboard.read"
                        },
                        new
                        {
                            Id = 9000,
                            Name = "role.create"
                        },
                        new
                        {
                            Id = 9010,
                            Name = "role.read"
                        },
                        new
                        {
                            Id = 9020,
                            Name = "role.update"
                        },
                        new
                        {
                            Id = 9030,
                            Name = "role.delete"
                        },
                        new
                        {
                            Id = 1000,
                            Name = "restaurant.read"
                        },
                        new
                        {
                            Id = 1010,
                            Name = "restaurant.update"
                        },
                        new
                        {
                            Id = 4000,
                            Name = "branch.read"
                        },
                        new
                        {
                            Id = 4010,
                            Name = "branch.update"
                        });
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Queuing", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid?>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Pax")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "Id");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Queuing");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Role", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.SelfOrderingPortal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("MaxUsage")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("UsageCount")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan?>("ValidDuration")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("SelfOrderingPortal");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.StaffPortal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("MaxUsage")
                        .HasColumnType("smallint");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("StaffId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("UsageCount")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan?>("ValidDuration")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "BranchId", "StaffId");

                    b.ToTable("StaffPortal");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.StaffRole", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<short>("StaffId")
                        .HasColumnType("smallint");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "StaffId", "RoleId");

                    b.HasIndex("RestaurantId", "RoleId");

                    b.ToTable("StaffRole");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.StaffUser", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "Id");

                    b.ToTable("StaffUser");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Stock", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<short>("IngredientId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "IngredientId");

                    b.HasIndex("RestaurantId", "IngredientId");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Table", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<short>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "BranchId", "Id");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Tag", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId", "Name");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Bill", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.ConsumerUser", "Consumer")
                        .WithMany("Bills")
                        .HasForeignKey("ConsumerId");

                    b.HasOne("FoodSphere.Common.Entities.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId", "BranchId", "IssuerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoodSphere.Common.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "BranchId", "TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consumer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.BillMember", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Bill", "Bill")
                        .WithMany("Members")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.ConsumerUser", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId");

                    b.Navigation("Bill");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Branch", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("FoodSphere.Common.Entities.Restaurant", "Restaurant")
                        .WithMany("Branches")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Ingredient", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Restaurant", "Restaurant")
                        .WithMany("Ingredient")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.IngredientTag", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientTags")
                        .HasForeignKey("RestaurantId", "IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.Tag", "Tag")
                        .WithMany("IngredientTags")
                        .HasForeignKey("RestaurantId", "TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Manager", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.MasterUser", "Master")
                        .WithMany("ManagedBranches")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.Branch", "Branch")
                        .WithMany("BranchManagers")
                        .HasForeignKey("RestaurantId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Master");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.ManagerRole", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.Manager", "ManagerBranch")
                        .WithMany("Roles")
                        .HasForeignKey("RestaurantId", "BranchId", "ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManagerBranch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Menu", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Restaurant", "Restaurant")
                        .WithMany("Menus")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.MenuComponent", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.Menu", "ChildMenu")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "ChildMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.Menu", "ParentMenu")
                        .WithMany("Components")
                        .HasForeignKey("RestaurantId", "ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildMenu");

                    b.Navigation("ParentMenu");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.MenuIngredient", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Ingredient", "Ingredient")
                        .WithMany("MenuIngredients")
                        .HasForeignKey("RestaurantId", "IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.Menu", "Menu")
                        .WithMany("MenuIngredients")
                        .HasForeignKey("RestaurantId", "MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.MenuTag", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Menu", "Menu")
                        .WithMany("MenuTags")
                        .HasForeignKey("RestaurantId", "MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.Tag", "Tag")
                        .WithMany("MenuTags")
                        .HasForeignKey("RestaurantId", "TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Order", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Bill", "Bill")
                        .WithMany("Orders")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.BillMember", "BillMember")
                        .WithMany("Orders")
                        .HasForeignKey("BillId", "BillMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoodSphere.Common.Entities.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId", "BranchId", "IssuerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bill");

                    b.Navigation("BillMember");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.OrderItem", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("BillId", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Queuing", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.ConsumerUser", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId");

                    b.HasOne("FoodSphere.Common.Entities.Branch", "Branch")
                        .WithMany("Queuings")
                        .HasForeignKey("RestaurantId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Restaurant", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.MasterUser", "Owner")
                        .WithMany("OwnedRestaurants")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Role", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.RolePermission", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RestaurantId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.SelfOrderingPortal", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Bill", "Bill")
                        .WithMany("Portals")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.StaffPortal", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.StaffUser", "StaffUser")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "BranchId", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.StaffRole", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.StaffUser", "Staff")
                        .WithMany("Roles")
                        .HasForeignKey("RestaurantId", "BranchId", "StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.StaffUser", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Branch", "Branch")
                        .WithMany("Staffs")
                        .HasForeignKey("RestaurantId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Stock", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Branch", "Branch")
                        .WithMany("IngredientStocks")
                        .HasForeignKey("RestaurantId", "BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Table", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Branch", "Branch")
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Tag", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.Restaurant", null)
                        .WithMany("Tags")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.MasterUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.MasterUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSphere.Common.Entities.MasterUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FoodSphere.Common.Entities.MasterUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Bill", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Orders");

                    b.Navigation("Portals");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.BillMember", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Branch", b =>
                {
                    b.Navigation("BranchManagers");

                    b.Navigation("IngredientStocks");

                    b.Navigation("Queuings");

                    b.Navigation("Staffs");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.ConsumerUser", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Ingredient", b =>
                {
                    b.Navigation("IngredientTags");

                    b.Navigation("MenuIngredients");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Manager", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.MasterUser", b =>
                {
                    b.Navigation("ManagedBranches");

                    b.Navigation("OwnedRestaurants");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Menu", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("MenuIngredients");

                    b.Navigation("MenuTags");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Restaurant", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Ingredient");

                    b.Navigation("Menus");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.StaffUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("FoodSphere.Common.Entities.Tag", b =>
                {
                    b.Navigation("IngredientTags");

                    b.Navigation("MenuTags");
                });
#pragma warning restore 612, 618
        }
    }
}
